"""create hardened observability schema

Revision ID: f196f3600b8c
Revises:
Create Date: 2026-07-14 23:20:00.705840
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f196f3600b8c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_traces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("execution_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("finish_idempotency_key", sa.String(length=96), nullable=True),
        sa.Column("finish_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','completed','failed','cancelled')",
            name=op.f("ck_execution_traces_valid_status"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_execution_traces_nonnegative_duration"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_traces")),
        sa.UniqueConstraint("tenant_id", "trace_id", name="uq_execution_traces_tenant_trace"),
    )
    op.create_index(
        op.f("ix_execution_traces_actor_id"), "execution_traces", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_execution_traces_execution_type"),
        "execution_traces",
        ["execution_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_traces_request_id"), "execution_traces", ["request_id"], unique=False
    )
    op.create_index(
        "ix_execution_traces_status_started",
        "execution_traces",
        ["status", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_traces_tenant_id"), "execution_traces", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_execution_traces_tenant_started",
        "execution_traces",
        ["tenant_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('guest','patient','doctor','admin')", name=op.f("ck_users_valid_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "external_id", name="uq_users_tenant_external"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "health_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_health_profiles_positive_version")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_health_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_profiles")),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_health_profiles_tenant_user"),
    )
    op.create_index(
        op.f("ix_health_profiles_tenant_id"), "health_profiles", ["tenant_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("context_summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','archived','deleted')", name=op.f("ck_sessions_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_tenant_id"), "sessions", ["tenant_id"], unique=False)
    op.create_index("ix_sessions_user_updated", "sessions", ["user_id", "updated_at"], unique=False)
    op.create_table(
        "trace_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=96), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_trace_events_nonnegative_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "trace_id"],
            ["execution_traces.tenant_id", "execution_traces.trace_id"],
            name=op.f("fk_trace_events_tenant_id_execution_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_events")),
        sa.UniqueConstraint("tenant_id", "trace_id", "event_id", name="uq_trace_events_event"),
        sa.UniqueConstraint("tenant_id", "trace_id", "sequence", name="uq_trace_events_sequence"),
    )
    op.create_index(
        op.f("ix_trace_events_event_type"), "trace_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_trace_events_tenant_id"), "trace_events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_trace_events_trace_created", "trace_events", ["trace_id", "created_at"], unique=False
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("rating", sa.String(length=16), nullable=False),
        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IN ('positive','negative')", name=op.f("ck_user_feedback_valid_rating")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "trace_id"],
            ["execution_traces.tenant_id", "execution_traces.trace_id"],
            name=op.f("fk_user_feedback_tenant_id_execution_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_feedback")),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_feedback_tenant_idempotency"),
    )
    op.create_index(op.f("ix_user_feedback_actor_id"), "user_feedback", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_user_feedback_tenant_id"), "user_feedback", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_user_feedback_trace_created", "user_feedback", ["trace_id", "created_at"], unique=False
    )
    op.create_table(
        "bad_cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("feedback_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "severity IN ('low','medium','high','critical')",
            name=op.f("ck_bad_cases_valid_severity"),
        ),
        sa.CheckConstraint(
            "source IN ('execution_failure','negative_feedback')",
            name=op.f("ck_bad_cases_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('open','triaged','resolved','dismissed')",
            name=op.f("ck_bad_cases_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["user_feedback.id"],
            name=op.f("fk_bad_cases_feedback_id_user_feedback"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "trace_id"],
            ["execution_traces.tenant_id", "execution_traces.trace_id"],
            name=op.f("fk_bad_cases_tenant_id_execution_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bad_cases")),
        sa.UniqueConstraint("tenant_id", "trace_id", "source", name="uq_bad_cases_trace_source"),
    )
    op.create_index(
        "ix_bad_cases_status_created", "bad_cases", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_bad_cases_tenant_id"), "bad_cases", ["tenant_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant','system','tool')", name=op.f("ck_messages_valid_role")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_messages_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    op.create_index(
        "ix_messages_tenant_session_created",
        "messages",
        ["tenant_id", "session_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_trace_id"), "messages", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_trace_id"), table_name="messages")
    op.drop_index("ix_messages_tenant_session_created", table_name="messages")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_bad_cases_tenant_id"), table_name="bad_cases")
    op.drop_index("ix_bad_cases_status_created", table_name="bad_cases")
    op.drop_table("bad_cases")
    op.drop_index("ix_user_feedback_trace_created", table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_tenant_id"), table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_actor_id"), table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index("ix_trace_events_trace_created", table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_tenant_id"), table_name="trace_events")
    op.drop_index(op.f("ix_trace_events_event_type"), table_name="trace_events")
    op.drop_table("trace_events")
    op.drop_index("ix_sessions_user_updated", table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_health_profiles_tenant_id"), table_name="health_profiles")
    op.drop_table("health_profiles")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_execution_traces_tenant_started", table_name="execution_traces")
    op.drop_index(op.f("ix_execution_traces_tenant_id"), table_name="execution_traces")
    op.drop_index("ix_execution_traces_status_started", table_name="execution_traces")
    op.drop_index(op.f("ix_execution_traces_request_id"), table_name="execution_traces")
    op.drop_index(op.f("ix_execution_traces_execution_type"), table_name="execution_traces")
    op.drop_index(op.f("ix_execution_traces_actor_id"), table_name="execution_traces")
    op.drop_table("execution_traces")
    # ### end Alembic commands ###
